# we are extending everything from tomcat:8.0 image ...
FROM tomcat:8.0

MAINTAINER sergey
# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY BookStore/target/bookstore.war /usr/local/tomcat/webapps/
